### ISSUE TITLE
How to Compile Legacy Compiler? AHK

### ISSUE THREAD

**Issue by sametydev** [CloakerSmoker/Relax-Language#4]
Hello,
How to compile legacy compiler (AHK) to Exe?

**Comment by CloakerSmoker** [comment]
I'm not sure how I forgot this for an entire year, but unfortunately "not planned" does match my plans. The AHK version is (and has been) legacy for so long that I can't even remember the answer anymore. I *think* that 500c0c5b67bd9cd46b04a13eef261c64ade85d8a might still run as AHK v1.

Either way, this language doesn't really have any usage beyond "I like the compiler because I wrote it". Are you looking for a project that compiles down to AHK for mcode and such? Because https://github.com/G33kDude/MCL.ahk is a much better option for that.
